ArjunBasandrai/elixir-chess-engine

- src/search.cpp
> feat: added reverse futility pruning

- elixir.cpp
- src/search.cpp
- src/search.h
Bench: 957900
Elo   | 9.19 +- 5.77 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 6352 W: 1534 L: 1366 D: 3452
Penta | [139, 725, 1328, 797, 187]
http://basandraiarjun.pythonanywhere.com/test/32/
> feat: added LMR

- src/search.cpp
Bench: 755971
Elo   | 4.26 +- 3.39 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 15268 W: 2989 L: 2802 D: 9477
Penta | [218, 1682, 3670, 1823, 241]
https://basandraiarjun.pythonanywhere.com/test/37/
> feat: added razoring

- src/uci.cpp
> fix: clear tt on receiving `ucinewgame` command

- src/search.cpp
- src/uci.cpp
> fix: fixed timed search hitting max-depth bug

- src/search.cpp
- src/tt.cpp
- src/tt.h
Bench: 675389
Elo   | 2.09 +- 3.94 (95%)
LLR   | 2.96 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 12160 W: 2519 L: 2446 D: 7195
Penta | [226, 1359, 2847, 1412, 236]
https://basandraiarjun.pythonanywhere.com/test/62/
> Tt refactor

- src/board/board.cpp
- src/board/board.h
- src/search.cpp
Bench: 719064
Elo   | 50.61 +- 14.60 (95%)
Games | N: 1044 W: 324 L: 173 D: 547
Penta | [15, 93, 185, 184, 45]
https://basandraiarjun.pythonanywhere.com/test/73/
> feat: added 3-fold repetition detection

- src/hashing/hash.cpp
- src/hashing/hash.h
> fix: use zobrist keys generated using xor-shifted seed

- src/movepicker.cpp
Bench: 955419
Elo   | 161.99 +- 30.00 (95%)
LLR   | 3.06 (-2.94, 2.94) [0.00, 5.00]
Games | N: 586 W: 386 L: 131 D: 69
Penta | [32, 30, 49, 15, 167]
https://basandraiarjun.pythonanywhere.com/test/100/
> feat: updated move ordering

- src/movepicker.cpp
Bench: 5520663
Elo   | 61.94 +- 17.50 (95%)
Games | N: 890 W: 334 L: 177 D: 379
Penta | [12, 74, 164, 135, 60]
https://basandraiarjun.pythonanywhere.com/test/140/
> feat: improved move ordering

- src/evaluate.cpp
Bench: 5793126
Elo   | 11.40 +- 6.79 (95%)
Games | N: 5520 W: 1606 L: 1425 D: 2489
Penta | [190, 616, 999, 733, 222]
https://basandraiarjun.pythonanywhere.com/test/159/
> feat: added tempo bonus

- src/search.cpp
Bench: 3596357
Elo   | 29.08 +- 11.64 (95%)
Games | N: 1940 W: 628 L: 466 D: 846
Penta | [51, 203, 342, 281, 93]
https://chess.aronpetkovski.com/test/283/
> feat: added lmp

- src/board/board.cpp
- src/board/board.h
Bench: 3596357
Elo   | 11.50 +- 8.10 (95%)
LLR   | 2.95 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 3870 W: 1124 L: 996 D: 1750
Penta | [115, 449, 721, 493, 157]
https://chess.aronpetkovski.com/test/289/
> refactor: use pieces array

- src/movegen.cpp
- src/search.cpp
- src/search.h
- src/uci.cpp
> fix: fixed stack overflow

- src/search.cpp
Bench: 2190907
Elo   | 45.17 +- 14.62 (95%)
LLR   | 3.01 (-2.94, 2.94) [0.00, 5.00]
Games | N: 1222 W: 419 L: 261 D: 542
Penta | [23, 111, 220, 199, 58]
https://chess.aronpetkovski.com/test/316/
> feat: use spsa tuned values for search

- src/search.cpp
> fix: do lmp before make move

- src/evaluate.cpp
- src/evaluate.h
- src/history.cpp
- src/movepicker.cpp
- src/search.cpp
- src/search.h
- src/uci.cpp
Bench: 721354
Elo   | 5.35 +- 4.20 (95%)
Games | N: 14420 W: 4067 L: 3845 D: 6508
Penta | [467, 1686, 2739, 1794, 524]
https://chess.aronpetkovski.com/test/430/
> Tuned search

- src/search.cpp
> feat: added mate distance pruning

- src/search.cpp
- src/tune.cpp
- src/tune.h
- src/uci.cpp
> chore: cleanups

- src/movepicker.h
- src/search.cpp
- src/search.h
> fix: fix null move on low time

- src/evaluate.cpp
- src/evaluate.h
> refactor: refactored eval

- src/search.cpp
- src/search.h
Passed STC
```
Elo   | 6.88 +- 4.77 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 5.00]
Games | N: 9598 W: 2440 L: 2250 D: 4908
Penta | [239, 1134, 1934, 1182, 310]
https://chess.aronpetkovski.com/test/917/
```
Bench: 578793
> feat: added improving heuristic for RFP

- src/uci.cpp
> feat: added `legals` command to uci

- src/board/board.cpp
- src/board/board.h
- src/uci.cpp
```
Elo   | 5.95 +- 4.26 (95%)
LLR   | 3.05 (-2.94, 2.94) [0.00, 5.00]
Games | N: 11678 W: 2842 L: 2642 D: 6194
Penta | [287, 1370, 2375, 1470, 337]
https://chess.aronpetkovski.com/test/1510/
```
Bench: 587559
> feat: use persistent history

- src/board/board.cpp
- src/board/board.h
- src/search.cpp
Elo   | 6.41 +- 4.50 (95%)
Games | N: 9646 W: 2246 L: 2068 D: 5332
Penta | [195, 1125, 2044, 1225, 234]
https://chess.aronpetkovski.com/test/1531/
Bench: 535679
> feat: added insufficent material detection

- src/search.cpp
```
Elo   | 6.42 +- 5.97 (95%)
LLR   | 2.99 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 6064 W: 1513 L: 1401 D: 3150
Penta | [158, 701, 1226, 765, 182]
https://chess.aronpetkovski.com/test/1616/
```
Bench: 472496
> refactor: refactored pvs

- src/search.cpp
- src/time_manager.cpp
- src/time_manager.h
- src/time_mananger.cpp
- src/uci.cpp
```
Elo   | 7.39 +- 4.82 (95%)
LLR   | 3.10 (-2.94, 2.94) [0.00, 5.00]
Games | N: 8462 W: 1940 L: 1760 D: 4762
Penta | [165, 985, 1811, 1045, 225]
https://chess.aronpetkovski.com/test/1626/
```
> Best Move Stability

- src/board/board.cpp
- src/board/board.h
- src/defs.h
- src/evaluate.cpp
- src/move.cpp
- src/move.h
- src/movepicker.cpp
- src/nnue/nnue.cpp
- src/nnue/nnue.h
- src/search.cpp
```
Elo   | 14.05 +- 7.07 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 3612 W: 802 L: 656 D: 2154
Penta | [64, 357, 838, 463, 84]
https://chess.aronpetkovski.com/test/1758/
```
> Efficient Updates to NN

- src/search.cpp
- src/ss.h
Elo   | 13.22 +- 6.60 (95%)
Games | N: 3444 W: 637 L: 506 D: 2301
Penta | [39, 318, 897, 409, 59]
https://chess.aronpetkovski.com/test/1813/
> Singular Extension

- src/search.cpp
```
Elo   | 8.96 +- 5.18 (95%)
Games | N: 5042 W: 883 L: 753 D: 3406
Penta | [33, 517, 1313, 603, 55]
https://chess.aronpetkovski.com/test/1827/
```
Bench: 352939
> feat: added multicut pruning

- src/nnue/nnue.h
> fix: increase accumulator stack size

- src/uci.cpp
```
Elo   | 2.72 +- 3.72 (95%)
LLR   | 3.01 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 9584 W: 1523 L: 1448 D: 6613
Penta | [91, 965, 2610, 1030, 96]
https://chess.aronpetkovski.com/test/2080/
```
> Separate input and search thread

- src/bench/bench.cpp
- src/search.h
- src/time_manager.cpp
- src/time_manager.h
- src/uci.cpp
> feat: updated time management

- src/board/board.cpp
- src/nnue/nnue.cpp
- src/nnue/nnue.h
> refactor: refactored nnue

- elixir.cpp
- src/board/board.h
- src/evaluate.cpp
- src/evaluate.h
- src/nnue/accumulator.h
- src/nnue/nnue.cpp
- src/nnue/nnue.h
> refactor: refactored nnue code

- src/bench/bench.cpp
- src/search.cpp
- src/search.h
- src/uci.cpp
> feat: added searcher class

- src/bench/bench.cpp
- src/board/board.cpp
- src/board/board.h
- src/movepicker.cpp
- src/movepicker.h
- src/nnue/nnue.h
- src/search.cpp
- src/search.h
- src/uci.cpp
```
Elo   | 4.69 +- 4.37 (95%)
LLR   | 2.89 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 5778 W: 818 L: 740 D: 4220
Penta | [38, 499, 1736, 579, 37]
https://chess.aronpetkovski.com/test/2324/
```
Bench: 378333
> Thread Data

- src/search.cpp
- src/search.h
> fix: fix node count reporting

- Makefile
- src/nnue/accumulator.h
- src/nnue/nnue.cpp
- src/nnue/simd.h
- src/nnue/weights.h
```
Elo   | 21.74 +- 6.33 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 3.00]
Games | N: 2752 W: 430 L: 258 D: 2064
Penta | [11, 183, 838, 311, 33]
https://chess.aronpetkovski.com/test/2439/
```
Bench: 378333
> feat: added simd

- src/board/board.cpp
- src/board/board.h
- src/utils/state.h
> chore: added pawn hash

- src/search.cpp
```
Elo   | 1.78 +- 1.43 (95%)
LLR   | 2.92 (-2.25, 2.89) [0.00, 3.00]
Games | N: 62154 W: 9564 L: 9246 D: 43344
Penta | [528, 6192, 17393, 6362, 602]
https://chess.aronpetkovski.com/test/2679/
```
Bench: 3454777
> feat: change return value of rfp

- src/tt.cpp
```
Elo   | 6.48 +- 3.43 (95%)
LLR   | 2.92 (-2.25, 2.89) [0.00, 3.00]
Games | N: 10836 W: 1766 L: 1564 D: 7506
Penta | [82, 1043, 2988, 1201, 104]
https://chess.aronpetkovski.com/test/2816/
```
Bench: 5030067
> feat: updated tt replacement policy

- src/search.cpp
```
Elo   | 1.11 +- 3.00 (95%)
LLR   | 2.93 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 15698 W: 2657 L: 2607 D: 10434
Penta | [181, 1635, 4173, 1673, 187]
https://chess.aronpetkovski.com/test/3524/
```
Bench: 4970492
> fix: add rfp guards

- src/search.cpp
```
Elo   | -0.15 +- 2.11 (95%)
LLR   | 2.91 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 31636 W: 5272 L: 5286 D: 21078
Penta | [348, 3403, 8365, 3319, 383]
https://chess.aronpetkovski.com/test/3510/
```
Bench: 4646666
> fix: use tt score only if it is usable

- src/search.cpp
```
Elo   | 8.62 +- 4.09 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 3.00]
Games | N: 8148 W: 2028 L: 1826 D: 4294
Penta | [37, 924, 1978, 1070, 65]
https://chess.aronpetkovski.com/test/3854/
````
Bench: 4763265
> feat: added negative extensions

- src/history.cpp
- src/history.h
- src/movepicker.cpp
- src/search.cpp
> refactor: refactored histories

- src/pv.h
- src/search.cpp
- src/search.h
- src/search_terms.cpp
- src/search_terms.h
> Search Refactor

- src/core/types.h
- src/search/history/continuation_history.h
- src/search/history/countermove_history.h
- src/search/history/quiet_history.h
> chore: moved histories from stack to heap

- src/core/tt/tt.h
- src/search/search.cpp
> fix: correct tt score before returning

- src/search/history/history.cpp
- src/search/history/history.h
```
Elo   | 3.73 +- 2.50 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 3.00]
Games | N: 21344 W: 4712 L: 4483 D: 12149
Penta | [121, 2453, 5312, 2648, 138]
https://chess.aronpetkovski.com/test/4249/
```
Bench: 5213750
> 4-ply Continuation History

- src/search/search.cpp
```
Elo   | 2.67 +- 2.00 (95%)
Games | N: 33528 W: 7188 L: 6930 D: 19410
Penta | [173, 3966, 8272, 4136, 217]
https://chess.aronpetkovski.com/test/4271/
```
Bench: 4920802
> feat: added negative extensions on cutnode

- src/search/search.cpp
> fix: dont use tt move in qsearch

- src/core/tt/tt.cpp
- src/core/tt/tt.h
- src/search/search.cpp
```
Elo   | 3.81 +- 4.07 (95%)
SPRT  | 8.0+0.08s Threads=4 Hash=64MB
LLR   | 2.89 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 6836 W: 1257 L: 1182 D: 4397
Penta | [18, 721, 1870, 786, 23]
https://chess.aronpetkovski.com/test/4354/
```
> TT static eval

- src/core/tt/tt.cpp
- src/search/search.cpp
```
Elo   | 14.40 +- 7.27 (95%)
LLR   | 2.93 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 2366 W: 509 L: 411 D: 1446
Penta | [13, 224, 607, 330, 9]
https://chess.aronpetkovski.com/test/4536/
```
> No fail low best move

- elixir.cpp
- src/core/board/board.cpp
- src/core/board/board.h
- src/utils/state.h
> chore: added non pawn hash and clear pawn hash on board clear

- src/search/search.cpp
> fix: fixed incorrectly set `soft_stop` variable
