ArjunBasandrai/elixir-chess-engine

- src/search.cpp
Bench: 907355
Elo   | 6.40 +- 4.51 (95%)
Games | N: 9234 W: 1959 L: 1789 D: 5486
Penta | [153, 1076, 2025, 1174, 189]
http://basandraiarjun.pythonanywhere.com/test/34/
> chore: updated lmr reduction factor

- src/board/board.cpp
- src/board/board.h
- src/movepicker.cpp
- src/search.cpp
Bench: 680261
Elo   | 12.91 +- 6.86 (95%)
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 3770 W: 792 L: 652 D: 2326
Penta | [45, 404, 869, 500, 67]
https://basandraiarjun.pythonanywhere.com/test/48/
> feat: added butterfly history heuristic

- src/board/board.h
Bench: 675389
Elo   | 4.38 +- 3.42 (95%)
Games | N: 15294 W: 3059 L: 2866 D: 9369
Penta | [260, 1708, 3534, 1869, 276]
https://basandraiarjun.pythonanywhere.com/test/58/
> feat: updated butterfly history formula to squared formula

- src/search.cpp
- src/search.h
Bench: 722496
Elo   | 11.78 +- 6.79 (95%)
Games | N: 4602 W: 1131 L: 975 D: 2496
Penta | [94, 507, 962, 625, 113]
https://basandraiarjun.pythonanywhere.com/test/66/
> refactor: use tt score for static eval in search.cpp

- src/movepicker.cpp
Bench: 1855006
Elo   | 30.74 +- 12.35 (95%)
LLR   | 2.63 (-2.94, 2.94) [0.00, 5.00]
Games | N: 1632 W: 508 L: 364 D: 760
Penta | [51, 139, 317, 233, 76]
https://chess.aronpetkovski.com/test/323/
> feat: added SEE move ordering

- src/search.cpp
Bench: 1915717
Elo   | 19.46 +- 9.29 (95%)
Games | N: 2788 W: 800 L: 644 D: 1344
Penta | [56, 316, 555, 350, 117]
https://chess.aronpetkovski.com/test/326/
> feat: added pvs see pruning

- src/search.cpp
Bench: 1195620
Elo   | 54.76 +- 15.98 (95%)
Games | N: 998 W: 348 L: 192 D: 458
Penta | [15, 88, 184, 150, 62]
https://chess.aronpetkovski.com/test/330/
> feat: added qsearch see pruning

- src/search.cpp
Bench: 1118904
Elo   | 3.53 +- 2.92 (95%)
Games | N: 29060 W: 7924 L: 7629 D: 13507
Penta | [916, 3480, 5496, 3669, 969]
https://chess.aronpetkovski.com/test/332/
> feat: added futility pruning

- src/search.cpp
- src/search.h
- src/tune.cpp
- src/uci.cpp
Bench: 721354
STC (10+0.1s) :
Elo   | 30.53 +- 16.47 (95%)
LLR   | 3.11 (-2.94, 2.94) [0.00, 10.00]
Games | N: 890 W: 269 L: 191 D: 430
Penta | [8, 96, 184, 124, 33]
https://chess.aronpetkovski.com/test/479/
LTC (60+0.6s) :
Elo   | 41.74 +- 18.87 (95%)
SPRT  | 60.0+0.60s Threads=1 Hash=64MB
LLR   | 2.97 (-2.94, 2.94) [0.00, 10.00]
Games | N: 644 W: 196 L: 119 D: 329
Penta | [8, 64, 119, 105, 26]
https://chess.aronpetkovski.com/test/481/
> Time Management

- src/board/board.cpp
Bench: 719099
Elo   | 14.28 +- 7.61 (95%)
Games | N: 3896 W: 1029 L: 869 D: 1998
Penta | [104, 408, 773, 550, 113]
https://chess.aronpetkovski.com/test/486/
> feat: use two-fold repetition rule instead of 3-fold

- src/history.cpp
- src/history.h
- src/movepicker.cpp
- src/search.cpp
Similarly to killer moves, the counter move list stores a move that caused a beta cutoff for each `stm-from-to` combination.
During move ordering, given the last played move, this counter move can then be retreived and used for better move ordering.
Passed STC:
```
Elo   | 12.65 +- 7.18 (95%)
LLR   | 3.07 (-2.94, 2.94) [0.00, 5.00]
Games | N: 4864 W: 1404 L: 1227 D: 2233
Penta | [138, 547, 937, 620, 190]
https://chess.aronpetkovski.com/test/638/
```
Bench: 684428
> Introduce counter moves for move ordering

- src/history.cpp
Elo   | 1.44 +- 3.74 (95%)
LLR   | 2.95 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 15462 W: 3747 L: 3683 D: 8032
Penta | [422, 1868, 3113, 1880, 448]
https://chess.aronpetkovski.com/test/1385/
Bench: 600953
> feat: added gravity to malus

- src/history.cpp
- src/history.h
```
Elo   | 14.67 +- 8.53 (95%)
LLR   | 2.96 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 2986 W: 782 L: 656 D: 1548
Penta | [64, 348, 577, 406, 98]
https://chess.aronpetkovski.com/test/1456/
```
Bench: 580582
> feat: updated history bonus formula

- Makefile
- src/history.cpp
- src/history.h
- src/movepicker.cpp
- src/movepicker.h
- src/search.cpp
- src/search.h
- src/ss.h
- src/types.h
```
Elo   | 4.80 +- 3.68 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 5.00]
Games | N: 15636 W: 3860 L: 3644 D: 8132
Penta | [390, 1832, 3225, 1914, 457]
https://chess.aronpetkovski.com/test/1464/
```
Bench: 530699
> feat: added 1 and 2 ply Continuation History

- src/history.cpp
- src/history.h
```
Elo   | 24.91 +- 9.89 (95%)
LLR   | 3.00 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2068 W: 572 L: 424 D: 1072
Penta | [35, 208, 433, 290, 68]
https://chess.aronpetkovski.com/test/1508/
```
Bench: 535679
> feat: added separate malus function

- src/search.cpp
Elo   | 32.09 +- 11.47 (95%)
Games | N: 1618 W: 468 L: 319 D: 831
Penta | [31, 151, 323, 246, 58]
https://chess.aronpetkovski.com/test/1535/
Bench: 589952
> feat: added history score based reduction in lmr

- src/evaluate.cpp
```
Elo   | 2.37 +- 1.81 (95%)
LLR   | 2.95 (-2.94, 2.94) [0.00, 3.00]
Games | N: 39854 W: 6228 L: 5956 D: 27670
Penta | [386, 3904, 11080, 4166, 391]
https://chess.aronpetkovski.com/test/2041/
```
Bench: 384294
> feat: added material scaling of evaluation

- src/search.cpp
```
Elo   | 4.31 +- 2.73 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 3.00]
Games | N: 17648 W: 2797 L: 2578 D: 12273
Penta | [156, 1733, 4863, 1880, 192]
https://chess.aronpetkovski.com/test/2072/
```
Bench: 379651
> feat: reduced singular extension beta

- Makefile
```
Elo   | 8.07 +- 3.70 (95%)
LLR   | 2.91 (-2.25, 2.89) [0.00, 3.00]
Games | N: 7406 W: 978 L: 806 D: 5622
Penta | [26, 590, 2330, 700, 57]
https://chess.aronpetkovski.com/test/2455/
```
Bench: 378333
> build: added link time optimization

- src/search.cpp
```
Elo   | 1.89 +- 1.49 (95%)
Games | N: 47498 W: 6133 L: 5875 D: 35490
Penta | [285, 4134, 14654, 4390, 286]
https://chess.aronpetkovski.com/test/2411/
```
Bench: 378334
> feat: added double extensions

- src/search.cpp
- src/tt.cpp
- src/tt.h
```
Elo   | 2.00 +- 1.59 (95%)
Games | N: 51254 W: 8040 L: 7745 D: 35469
Penta | [490, 5100, 14135, 5429, 473]
https://chess.aronpetkovski.com/test/2799/
```
Bench: 4898086
> feat: added ttpv reduction to lmr

- src/search.cpp
```
Elo   | 1.76 +- 1.42 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 3.00]
Games | N: 63646 W: 9821 L: 9498 D: 44327
Penta | [574, 6328, 17716, 6611, 594]
https://chess.aronpetkovski.com/test/2781/
```
Bench: 4398444
> feat: changed nmp reduction formula

- src/search.cpp
- src/tt.cpp
- src/tt.h
```
Elo   | 7.12 +- 3.66 (95%)
Games | N: 9854 W: 1662 L: 1460 D: 6732
Penta | [93, 909, 2746, 1061, 118]
https://chess.aronpetkovski.com/test/2817/
```
Bench: 4854669
> feat: use improving heuristic in tt replacement policy

- src/board/board.h
- src/search.cpp
```
Elo   | 1.76 +- 1.42 (95%)
LLR   | 2.94 (-2.25, 2.89) [0.00, 3.00]
Games | N: 69016 W: 11687 L: 11337 D: 45992
Penta | [737, 7208, 18310, 7474, 779]
https://chess.aronpetkovski.com/test/2856/
```
Bench: 4652523
> feat: only do nmp if board has non pawn material

- src/search.cpp
- src/search.h
```
Elo   | 1.36 +- 1.08 (95%)
LLR   | 2.95 (-2.25, 2.89) [0.00, 3.00]
Games | N: 118272 W: 19541 L: 19077 D: 79654
Penta | [1251, 12279, 31646, 12675, 1285]
https://chess.aronpetkovski.com/test/2850/
```
Bench: 5351898
> feat: updated rfp margin formula

- src/search.cpp
```
Elo   | 3.63 +- 2.48 (95%)
LLR   | 2.92 (-2.25, 2.89) [0.00, 3.00]
Games | N: 23558 W: 4131 L: 3885 D: 15542
Penta | [261, 2471, 6114, 2627, 306]
https://chess.aronpetkovski.com/test/2886/
```
Bench: 4819066
> feat: use tt score in qs

- src/search.cpp
```
Elo   | 2.78 +- 2.06 (95%)
LLR   | 2.95 (-2.25, 2.89) [0.00, 3.00]
Games | N: 34184 W: 6087 L: 5813 D: 22284
Penta | [362, 3688, 8798, 3802, 442]
https://chess.aronpetkovski.com/test/2895/
```
Bench: 4612599
> feat: only do lmp if board has non pawn material

- src/search.cpp
```
Elo   | 0.01 +- 2.27 (95%)
LLR   | 2.90 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 27790 W: 4802 L: 4801 D: 18187
Penta | [321, 3006, 7230, 3027, 311]
https://chess.aronpetkovski.com/test/3055/
```
Bench: 4612610
> fix: dont use exact flag in qs

- src/search.cpp
```
Elo   | 4.17 +- 2.68 (95%)
Games | N: 18658 W: 3110 L: 2886 D: 12662
Penta | [183, 1862, 5005, 2106, 173]
https://chess.aronpetkovski.com/test/3273/
```
Bench: 4772842
> feat: added board phase in nmp reduction

- src/defs.h
- src/search.cpp
- src/ss.h
```
Elo   | 1.56 +- 3.26 (95%)
LLR   | 2.91 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 13148 W: 2211 L: 2152 D: 8785
Penta | [134, 1394, 3484, 1403, 159]
https://chess.aronpetkovski.com/test/3503/
```
Bench: 4950344
> fix: fixed search stack eval

- src/search.cpp
```
Elo   | 4.05 +- 4.56 (95%)
LLR   | 3.04 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 7900 W: 2131 L: 2039 D: 3730
Penta | [103, 933, 1793, 1011, 110]
https://chess.aronpetkovski.com/test/3586/
```
Bench: 5738653
> fix: use tt score only when it is valid in qs

- src/search.cpp
```
Elo   | 2.68 +- 2.01 (95%)
Games | N: 33648 W: 8159 L: 7899 D: 17590
Penta | [196, 3976, 8256, 4164, 232]
https://chess.aronpetkovski.com/test/3836/
```
Bench: 4959499
> feat: added improving heuristic to lmp

- Makefile
- src/texel/texel.cpp
```
Elo   | 15.11 +- 5.53 (95%)
Games | N: 4418 W: 1136 L: 944 D: 2338
Penta | [19, 452, 1100, 594, 44]
https://chess.aronpetkovski.com/test/4078/
```
Bench: 4959499
> feat: added compiler optimizations

- src/search/search.cpp
```
Elo   | 4.85 +- 2.96 (95%)
Games | N: 15830 W: 3598 L: 3377 D: 8855
Penta | [107, 1808, 3885, 1987, 128]
https://chess.aronpetkovski.com/test/4235/
```
Bench: 5380812
> feat: added improving heuristic to lmr

- src/search/search.cpp
- src/search/ss.h
```
Elo   | 0.81 +- 2.69 (95%)
LLR   | 2.90 (-2.25, 2.89) [-5.00, 0.00]
Games | N: 17232 W: 3327 L: 3287 D: 10618
Penta | [78, 1983, 4450, 2031, 74]
https://chess.aronpetkovski.com/test/4303/
```
Bench: 5089472
> fix: fixed static eval

- src/search/search.cpp
```
Elo   | 2.64 +- 1.96 (95%)
Games | N: 32686 W: 6504 L: 6256 D: 19926
Penta | [146, 3679, 8468, 3881, 169]
https://chess.aronpetkovski.com/test/4325/
```
Bench: 5590737
> feat: updated nmp guard

- src/search/history/correction_history.h
- src/search/history/history.cpp
- src/search/history/history.h
- src/search/history/history_formulas.h
- src/search/search.cpp
```
Elo   | 5.03 +- 2.95 (95%)
LLR   | 2.89 (-2.25, 2.89) [0.00, 3.00]
Games | N: 14018 W: 2849 L: 2646 D: 8523
Penta | [54, 1518, 3675, 1695, 67]
https://chess.aronpetkovski.com/test/4544/
```
Bench: 3619001
> feat: added correction history

- src/core/types.h
- src/search/history/history.cpp
- src/search/history/history.h
- src/search/history/quiet_history.h
- src/search/search.cpp
```
Elo   | 3.11 +- 2.20 (95%)
Games | N: 26346 W: 5486 L: 5250 D: 15610
Penta | [123, 3007, 6684, 3229, 130]
https://chess.aronpetkovski.com/test/5878/
```
Bench: 3616285
> feat: made the quiet history bigger

- src/search/search.cpp
```
Elo   | 3.66 +- 2.45 (95%)
Games | N: 21342 W: 4522 L: 4297 D: 12523
Penta | [104, 2405, 5449, 2588, 125]
https://chess.aronpetkovski.com/test/5879/
```
Bench: 3698290
> feat: reduce capture moves less in LMR
